sudo: false
language: java
dist: trusty
jdk:
  - oraclejdk11
  - openjdk11
install:
  - mvn -v
  - mvn -B install -U -DskipTests=true

cache:
  directories:
    - "${HOME}/.m2"

branches:
  only:
    - master

